root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: documentation
        permanent: true

app_web:
    resource: '@AppBundle/Controller/Web'
    type: annotation

app_api:
    resource: '@AppBundle/Controller/Api'
    type: annotation
    defaults:
      _format: json